language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.pip
# command to run tests
script:
  - pytest src/test.py # or py.test for Python versions 3.5 and below
